#!/bin/bash

clear

cmake .

if [[ $? -ne 0 ]]
then
  exit 1
fi

if [[ $HOSTNAME == "archbox" ]]
then
  make -j4
else
  make
fi

if [[ $? -ne 0 ]]
then
  exit 1
fi

if [[ $HOSTNAME == "archbox" || $HOSTNAME == "mintvm" ]]
then
  ./game
fi

exit 0

